#!/usr/bin/env bun
// Bundle the Solid frontend into anime_tools/gui/static/: index.html plus the
// assets it points at (today: one woff2).
//
// Git installs (`uv tool install ... git+...`) ship this directory as committed
// and the wheel's package-data is `static/*`, so whatever lands here is what
// runs -- there is no toolchain on the far side to rebuild it. Script and
// stylesheet therefore go INSIDE index.html: they are the half that changes
// every commit, and one file means one artifact to keep in sync. The font does
// not. Inlined as a base64 `data:` URL it was 2.25 MB of a 2.45 MB bundle --
// 92% of a blob git had to store anew for a one-line CSS edit -- so it is
// written beside index.html instead, served from /assets/<name> (the flat
// layout is what `static/*` globs), and stays one immutable object in history.
// Bun's bundler already emits it as a separate artifact and rewrites the
// url() to it; this script keeps that split and folds back only the rest.
import { unlink } from "node:fs/promises";
import { solidPlugin } from "./solid-plugin";

const OUT_DIR = "../anime_tools/gui/static";
const OUT = `${OUT_DIR}/index.html`;

const result = await Bun.build({
  entrypoints: ["./src/index.tsx"],
  plugins: [solidPlugin()],
  target: "browser",
  format: "esm",
  minify: true,
  sourcemap: "none",
  // Name assets for their source, not their content: a hashed name would make
  // a font bump a new file and leave the old one in the committed directory.
  naming: { asset: "[name].[ext]" },
});
if (!result.success) {
  for (const log of result.logs) console.error(String(log));
  process.exit(1);
}

let js = "";
let css = "";
// Assets Bun split out of the CSS (the woff2), keyed by the filename it
// rewrote the url() to.
const assets = new Map<string, Uint8Array>();

for (const out of result.outputs) {
  // Bun reports artifact paths with the host separator (`.\font.woff2` on
  // Windows); the url() it rewrote into the CSS is always POSIX, so normalize
  // the name before matching one against the other.
  const name = out.path.replaceAll("\\", "/").replace(/^\.\//, "");
  if (out.kind === "entry-point") js = await out.text();
  else if (name.endsWith(".css")) css += await out.text();
  else assets.set(name, new Uint8Array(await out.arrayBuffer()));
}
if (!js) throw new Error("no entry-point artifact");
if (!css) throw new Error("no css artifact -- did src/index.tsx stop importing styles.css?");

// Write every asset the CSS points at beside index.html and re-anchor the
// url() at the route that serves it. Bun writes the reference relative to the
// stylesheet, which would resolve against "/" once the CSS is inlined into the
// page -- correct today, but only by coincidence, so name the route outright.
// One `replace` pass and not two `replaceAll`s: the replacement now CONTAINS
// the name, and a second sweep would nest it (`/assets//assets/font.woff2`).
const written = new Set(["index.html"]);
for (const [name, bytes] of assets) {
  const ref = new RegExp(`(?:\\./)?${name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`, "g");
  const before = css;
  css = css.replace(ref, `/assets/${name}`);
  if (css === before) throw new Error(`asset ${name} is not referenced by the bundled CSS`);
  await Bun.write(`${OUT_DIR}/${name}`, bytes);
  written.add(name);
}

// An asset that stops being referenced would otherwise sit in the committed
// directory forever: CI diffs this tree, and a file nothing writes never drifts.
for (const stale of new Bun.Glob("*").scanSync(OUT_DIR)) {
  if (written.has(stale)) continue;
  await unlink(`${OUT_DIR}/${stale}`);
  console.log(`removed stale ${stale}`);
}

// A literal `</script` inside the payload would close the tag early; in JS,
// `<\/` is the same string. CSS has no such escape, so assert instead -- today
// nothing in styles.css or the base64 font can produce it.
const safe = (s: string) => s.replaceAll("</", "<\\/");
if (/<\/style/i.test(css)) throw new Error("bundled CSS contains `</style` and cannot be inlined");

// frontend/fonts/README.md is not installed anywhere, so the font's attribution
// has to ride in what the wheel does ship -- and it ships this page beside the
// woff2 itself.
const NOTICE = `<!--\n  anime_tools GUI - generated by frontend/build.ts, do not edit.\n  Bundled font (served from /assets): Pretendard (c) 2021 Kil Hyung-jin,\n  SIL Open Font License 1.1 - https://github.com/orioncactus/pretendard\n-->`;

let html = await Bun.file("index.html").text();
const tag = /\s*<script type="module" src="\/src\/index\.tsx"><\/script>/;
if (!tag.test(html)) throw new Error("index.html no longer has the /src/index.tsx script tag");
html = html
  .replace(tag, "")
  .replace("<!doctype html>", `<!doctype html>\n${NOTICE}`)
  .replace("</head>", `<style>${css.trim()}</style>\n</head>`)
  .replace("</body>", `<script type="module">${safe(js).trim()}</script>\n</body>`);

await Bun.write(OUT, html);

const kb = (n: number) => `${(n / 1024).toFixed(0)} KB`;
console.log(`${OUT}  ${kb(Buffer.byteLength(html))}  (js ${kb(js.length)}, css ${kb(css.length)})`);
for (const [name, bytes] of assets) console.log(`${OUT_DIR}/${name}  ${kb(bytes.length)}`);
