#!/usr/bin/env bun
// Bundle the Solid frontend into ONE self-contained
// anime_tools/gui/static/index.html.
//
// The server only routes "/", the wheel's package-data is `static/*`, and git
// installs (`uv tool install ... git+...`) ship the committed file as-is -- so
// script, stylesheet and font all end up inline, with nothing left to fetch.
// Bun's bundler emits them as separate artifacts and rewrites the references;
// this script folds them back together.
import { solidPlugin } from "./solid-plugin";

const OUT = "../anime_tools/gui/static/index.html";

const result = await Bun.build({
  entrypoints: ["./src/index.tsx"],
  plugins: [solidPlugin()],
  target: "browser",
  format: "esm",
  minify: true,
  sourcemap: "none",
});
if (!result.success) {
  for (const log of result.logs) console.error(String(log));
  process.exit(1);
}

let js = "";
let css = "";
// Assets Bun split out of the CSS (the woff2), keyed by the hashed filename it
// rewrote the url() to.
const assets = new Map<string, { type: string; bytes: Uint8Array }>();

for (const out of result.outputs) {
  // Bun reports artifact paths with the host separator (`.\font.woff2` on
  // Windows); the url() it rewrote into the CSS is always POSIX, so normalize
  // the name before matching one against the other.
  const name = out.path.replaceAll("\\", "/").replace(/^\.\//, "");
  if (out.kind === "entry-point") js = await out.text();
  else if (name.endsWith(".css")) css += await out.text();
  else assets.set(name, { type: out.type, bytes: new Uint8Array(await out.arrayBuffer()) });
}
if (!js) throw new Error("no entry-point artifact");
if (!css) throw new Error("no css artifact -- did src/index.tsx stop importing styles.css?");

// Inline every asset the CSS still points at. `format(woff2)` survives; only
// the url() target changes, so @font-face keeps working with zero requests.
for (const [name, asset] of assets) {
  const dataUrl = `data:${asset.type.split(";")[0]};base64,${Buffer.from(asset.bytes).toString("base64")}`;
  const before = css;
  css = css.replaceAll(`./${name}`, dataUrl).replaceAll(name, dataUrl);
  if (css === before) throw new Error(`asset ${name} is not referenced by the bundled CSS`);
}

// A literal `</script` inside the payload would close the tag early; in JS,
// `<\/` is the same string. CSS has no such escape, so assert instead -- today
// nothing in styles.css or the base64 font can produce it.
const safe = (s: string) => s.replaceAll("</", "<\\/");
if (/<\/style/i.test(css)) throw new Error("bundled CSS contains `</style` and cannot be inlined");

// The wheel ships this one file and nothing else, so the embedded font's
// attribution has to ride along with it (frontend/fonts/README.md is not
// installed anywhere).
const NOTICE = `<!--\n  anime_tools GUI - generated by frontend/build.ts, do not edit.\n  Embedded font: Pretendard (c) 2021 Kil Hyung-jin, SIL Open Font License 1.1\n  https://github.com/orioncactus/pretendard\n-->`;

let html = await Bun.file("index.html").text();
const tag = /\s*<script type="module" src="\/src\/index\.tsx"><\/script>/;
if (!tag.test(html)) throw new Error("index.html no longer has the /src/index.tsx script tag");
html = html
  .replace(tag, "")
  .replace("<!doctype html>", `<!doctype html>\n${NOTICE}`)
  .replace("</head>", `<style>${css.trim()}</style>\n</head>`)
  .replace("</body>", `<script type="module">${safe(js).trim()}</script>\n</body>`);

await Bun.write(OUT, html);

const kb = (n: number) => `${(n / 1024).toFixed(0)} KB`;
console.log(
  `${OUT}  ${kb(Buffer.byteLength(html))}  (js ${kb(js.length)}, css+font ${kb(css.length)})`,
);
