import { createEffect, createMemo, createSignal, For, Index, on, Show } from "solid-js";
import { api } from "../api";
import { CaptionCard } from "./CaptionCard";
import type { CaptionEntry, ImageInfo, ItemDetail, NodeKind } from "../types";

type View = "image" | "resized" | "mask";
const VIEWS: View[] = ["image", "resized", "mask"];
const VIEW_LABEL: Record<View, string> = {
  image: "source",
  resized: "resized",
  mask: "mask",
};

const dims = (i: ImageInfo | null) =>
  i ? `${i.width ?? "?"}×${i.height ?? "?"} · ${(i.bytes / 1024).toFixed(0)} KB` : "";

export function ItemView(props: {
  item?: ItemDetail;
  loading: boolean;
  error?: string;
  kind: NodeKind;
  onSaved: (entry: CaptionEntry) => void;
}) {
  const [view, setView] = createSignal<View>("image");
  const available = createMemo(() => VIEWS.filter((v) => props.item?.[v]));
  // Keep the toggle on something that exists as the selection moves.
  createEffect(
    on(
      () => props.item,
      () => {
        if (!available().includes(view())) setView(available()[0] ?? "image");
      },
    ),
  );
  const shown = () => props.item?.[view()] ?? null;

  // Picking `variants` in the tree has to bring its card into view, the same
  // way CaptionCard does for the two editable ones.
  let variantsCard!: HTMLDivElement;
  createEffect(() => {
    if (props.kind === "variants" && props.item)
      variantsCard?.scrollIntoView({ block: "nearest", behavior: "smooth" });
  });

  return (
    <main>
      <Show
        when={props.item}
        fallback={
          <div class="empty">
            <Show when={props.error} fallback={props.loading ? "loading…" : "Pick an image on the left."}>
              <span class="err">{props.error}</span>
            </Show>
          </div>
        }
      >
        {(it) => (
          <>
            <div class="crumbs">
              <Show when={it().dir}>
                <span class="dim">{it().dir}/</span>
              </Show>
              <b>{it().name}</b>
              <span class="sp" />
              <span class="dim">{dims(it().image)}</span>
            </div>

            <div class="split">
              <div class="preview">
                <div class="tabs sub">
                  <For each={VIEWS}>
                    {(v) => (
                      <a
                        classList={{ sel: view() === v, na: !it()[v] }}
                        onClick={() => it()[v] && setView(v)}
                        title={it()[v]?.path ?? "not generated"}
                      >
                        {VIEW_LABEL[v]}
                      </a>
                    )}
                  </For>
                </div>
                <Show
                  when={shown()}
                  fallback={<div class="empty dim">no {VIEW_LABEL[view()]} for this image</div>}
                >
                  {(img) => (
                    <>
                      <a class="frame" href={api.fileUrl(img().path)} target="_blank">
                        <img src={api.fileUrl(img().path)} alt={it().rel} />
                      </a>
                      <div class="dim hint mono">
                        {img().path} · {dims(img())}
                      </div>
                    </>
                  )}
                </Show>
              </div>

              <div class="captions">
                {/* Index, not For: the pair is fixed and in fixed order, so a
                    saved entry should update its card, not replace it. */}
                <Index each={it().captions}>
                  {(c) => (
                    <CaptionCard
                      rel={it().rel}
                      entry={c()}
                      selected={props.kind === c().kind}
                      onSaved={props.onSaved}
                    />
                  )}
                </Index>

                <div classList={{ card: true, sel: props.kind === "variants" }} ref={variantsCard}>
                  <div class="card-h">
                    <span class="dot variants" />
                    <b>variants</b>
                    <span class="dim path" title={it().variants.path}>
                      {it().variants.path}
                    </span>
                    <span class="sp" />
                    <span class="badge">read-only</span>
                  </div>
                  <div class="dim hint">
                    Generated by the correct stage — v0 is the pristine derived caption. Hand edits
                    here are overwritten.
                  </div>
                  <Show
                    when={it().variants.rows.length}
                    fallback={<div class="dim hint">no sidecar</div>}
                  >
                    <table class="variants">
                      <tbody>
                        <For each={it().variants.rows}>
                          {(r) => (
                            <tr>
                              <td class="vlabel">{r.label}</td>
                              <td>{r.text}</td>
                            </tr>
                          )}
                        </For>
                      </tbody>
                    </table>
                  </Show>
                </div>
              </div>
            </div>
          </>
        )}
      </Show>
    </main>
  );
}
