import { For, Show } from "solid-js";
import { t } from "../i18n";
import type { OcrLine } from "../types";

/** What the OCR stage read out of the picture — the `{stem}.ocr.txt` sidecar.
    Not a rung of the caption ladder: no badge, no editor, nothing to click into
    the caption, since these are the words in the image rather than a text the
    caption could be made to say. Read-only; the sidecar is regenerated by
    re-running the stage. */
export function OcrPanel(props: { lines: OcrLine[] }) {
  return (
    <Show when={props.lines.length}>
      <div class="card ocr">
        <div class="card-h">
          <b>{t().ocr.title}</b>
          <span class="badge">{t().ocr.count(props.lines.length)}</span>
          <span class="dim">{t().ocr.readOnly}</span>
        </div>
        <table class="ocrlines">
          <tbody>
            <For each={props.lines}>
              {(line) => (
                <tr>
                  <td class="dim seq">{line.seq}</td>
                  <td class="text">{line.text}</td>
                  {/* No score column: the VL reader answers text, not a
                      confidence, so the sidecar's score is always 0.000. */}
                  <td class="dim box mono" title={t().ocr.boxHint}>
                    {line.box[0]},{line.box[1]}
                  </td>
                </tr>
              )}
            </For>
          </tbody>
        </table>
      </div>
    </Show>
  );
}
