import { For, Show } from "solid-js";
import { api } from "../api";
import { t } from "../i18n";
import type { ImageInfo, OcrLine } from "../types";

/** What the OCR stage read out of the picture — the `{stem}.ocr.txt` sidecar.
    Not a rung of the caption ladder: no editor, nothing to click into the
    caption, since these are the words in the image rather than a text the
    caption could be made to say. Read-only; the sidecar is regenerated by
    re-running the stage.

    Every line is a badge, and a badge is a place in the picture: clicking one
    puts the preview on the boxes view with that line's box drawn alone
    (`OcrBoxes`), which is the only way to tell a misread from a box that was
    never text. The count in the header is the same switch for all of them. */
export function OcrPanel(props: {
  lines: OcrLine[];
  /** The preview is on the boxes view — the header badge is that toggle. */
  on: boolean;
  /** Which line is drawn alone, by `seq`; null is every box at once. */
  focus: number | null;
  /** There is an image with known pixels to draw the boxes over. Without one
      the badges are inert: a box has nowhere to land. */
  can: boolean;
  onShow: (seq: number | null) => void;
}) {
  return (
    <Show when={props.lines.length}>
      <div class="card ocr">
        <div class="card-h">
          <b>{t().ocr.title}</b>
          <button
            classList={{ badge: true, boxes: true, on: props.on }}
            disabled={!props.can}
            title={props.can ? t().ocr.boxesHint : t().ocr.boxesNeeds}
            onClick={() => props.onShow(null)}
          >
            {/* The glyph is what the button does; the count is what it has. */}□{" "}
            {t().ocr.count(props.lines.length)}
          </button>
          <span class="dim">{t().ocr.readOnly}</span>
        </div>
        <table class="ocrlines">
          <tbody>
            <For each={props.lines}>
              {(line) => (
                <tr classList={{ sel: props.on && props.focus === line.seq }}>
                  <td>
                    <button
                      classList={{
                        seqbadge: true,
                        weak: !line.usable,
                        on: props.on && props.focus === line.seq,
                      }}
                      disabled={!props.can}
                      title={props.can ? t().ocr.showBox(line.seq) : t().ocr.boxesNeeds}
                      onClick={() => props.onShow(line.seq)}
                    >
                      {line.seq}
                    </button>
                  </td>
                  <td classList={{ text: true, weak: !line.usable }}>
                    {line.text}
                    {/* Why a line the sidecar kept will not reach a caption —
                        the floors are the server's answer, not a sum done
                        here. */}
                    <Show when={!line.usable}>
                      {" "}
                      <span class="badge warn" title={t().ocr.weakHint}>
                        {t().ocr.weak}
                      </span>
                    </Show>
                  </td>
                  <td class="dim box mono" title={t().ocr.scores(line.det, line.score)}>
                    {line.box[0]},{line.box[1]}
                  </td>
                </tr>
              )}
            </For>
          </tbody>
        </table>
      </div>
    </Show>
  );
}

/** The detector's boxes over the pixels they were found in.

    The coordinates are the *resized* copy's own — that is the tree the OCR
    stage walks — so the base is that copy and never the source: resize
    cover-crops, and a box drawn over the uncropped original would point at the
    wrong glyphs. The `<svg>` carries the base's pixel size as its `viewBox`
    and letterboxes with `meet`, which is exactly what `object-fit:contain`
    does to the image under it, so a box lands on its text at every frame size
    and every zoom without one measurement here. */
export function OcrBoxes(props: {
  base: ImageInfo;
  lines: OcrLine[];
  focus: number | null;
  /** The frame's zoom/pan transform, applied to picture and boxes together. */
  style: Record<string, string>;
}) {
  const w = () => props.base.width ?? 0;
  const h = () => props.base.height ?? 0;
  // The seq label rides in image pixels like the box it names, so it keeps its
  // size relative to the text it points at rather than to the window.
  const label = () => Math.max(10, Math.round(h() / 44));
  return (
    <div class="overlay" style={props.style}>
      <img src={api.fileUrl(props.base.path)} alt="" draggable={false} />
      <svg class="boxes" viewBox={`0 0 ${w()} ${h()}`} preserveAspectRatio="xMidYMid meet">
        <For each={props.lines}>
          {(line) => (
            <g
              classList={{
                weak: !line.usable,
                off: props.focus !== null && props.focus !== line.seq,
                on: props.focus === line.seq,
              }}
            >
              <rect
                x={line.box[0]}
                y={line.box[1]}
                width={line.box[2] - line.box[0]}
                height={line.box[3] - line.box[1]}
                vector-effect="non-scaling-stroke"
              />
              <text
                x={line.box[0] + label() * 0.3}
                y={line.box[1] - label() * 0.3}
                font-size={`${label()}`}
              >
                {line.seq}
              </text>
            </g>
          )}
        </For>
      </svg>
    </div>
  );
}
