"""The double-clickable launcher, one file per platform.

``uv tool install`` puts ``anime-tools-gui`` on PATH and leaves no folder behind
to launch it from, but the GUI reads its curation home from the working
directory (:func:`anime_tools._env.curation_home`) — so the launcher is a
per-dataset-folder file whose whole content is "run the GUI *here*", with the
folder's absolute path pinned as its working directory. Copy it to the desktop
and it still opens that dataset; move the dataset and re-run this to point at
the new path.

Windows gets an ``.lnk`` (the only real shortcut format, written through
``WScript.Shell`` since Python cannot author one), macOS a ``chmod +x``
``.command`` that Finder opens in Terminal, everything else a ``.desktop``
entry with ``Terminal=true``.

The bootstrap installers call ``anime-tools-shortcut`` in the directory they ran
in, best-effort — a launcher is a convenience and never a reason to fail an
install. Stdlib only and torch-free.
"""

from __future__ import annotations

import argparse
import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

LAUNCHER_NAME = "Anime Tools GUI"
DESCRIPTION = "anime_tools web GUI, opened on this dataset folder"
GUI_SCRIPT = "anime-tools-gui"
GUI_ARGS = ("--open",)

#: Marks the generated file as ours, so a rewrite is obviously a rewrite.
_BANNER = "generated by `anime-tools-shortcut` — safe to delete or copy elsewhere"


class ShortcutError(RuntimeError):
    """The launcher could not be written."""


def gui_command() -> list[str]:
    """The argv a launcher runs: the console script, or the module behind it.

    ``anime-tools-gui`` lives beside the interpreter running this (the tool
    environment's ``bin`` / ``Scripts``); PATH is the fallback for a venv whose
    scripts sit elsewhere, and ``python -m anime_tools.gui`` for an install that
    has no console script at all.
    """
    suffix = ".exe" if sys.platform == "win32" else ""
    local = Path(sys.executable).parent / f"{GUI_SCRIPT}{suffix}"
    if local.is_file():
        return [str(local), *GUI_ARGS]
    found = shutil.which(GUI_SCRIPT)
    if found:
        return [str(Path(found).resolve()), *GUI_ARGS]
    return [sys.executable, "-m", "anime_tools.gui", *GUI_ARGS]


def launcher_path(directory: Path) -> Path:
    """Where the launcher for ``directory`` lands, extension and all."""
    ext = {"win32": ".lnk", "darwin": ".command"}.get(sys.platform, ".desktop")
    return directory / f"{LAUNCHER_NAME}{ext}"


def _write_lnk(path: Path, directory: Path, command: list[str]) -> None:
    """A real ``.lnk``, via the shell COM object PowerShell can reach.

    Paths travel in the environment rather than the command string: a user
    profile with a quote or a ``$`` in it is a broken script otherwise.
    """
    if not shutil.which("powershell"):
        raise ShortcutError("powershell not found; cannot write a .lnk")
    env = {
        **os.environ,
        "_SC_PATH": str(path),
        "_SC_TARGET": command[0],
        "_SC_ARGS": subprocess.list2cmdline(command[1:]),
        "_SC_WD": str(directory),
        "_SC_DESC": DESCRIPTION,
    }
    ps = (
        "$ws = New-Object -ComObject WScript.Shell;"
        "$sc = $ws.CreateShortcut($env:_SC_PATH);"
        "$sc.TargetPath = $env:_SC_TARGET;"
        "$sc.Arguments = $env:_SC_ARGS;"
        "$sc.WorkingDirectory = $env:_SC_WD;"
        "$sc.Description = $env:_SC_DESC;"
        "$sc.Save()"
    )
    done = subprocess.run(
        ["powershell", "-NoProfile", "-NonInteractive", "-Command", ps],
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    if done.returncode != 0 or not path.is_file():
        raise ShortcutError(
            (done.stderr or done.stdout).strip() or "WScript.Shell failed"
        )


def _write_command(path: Path, directory: Path, command: list[str]) -> None:
    """macOS: an executable ``.command``, which Finder runs in Terminal."""
    body = "\n".join(
        [
            "#!/bin/sh",
            f"# {LAUNCHER_NAME} — {_BANNER}",
            f"cd {shlex.quote(str(directory))} || exit 1",
            f"exec {shlex.join(command)}",
            "",
        ]
    )
    path.write_text(body, encoding="utf-8")
    path.chmod(0o755)


def _desktop_quote(command: list[str]) -> str:
    """Quote an argv for a Desktop Entry ``Exec=``.

    The spec's quoting is double quotes with backslash escapes — not POSIX
    shell quoting, so :mod:`shlex` is the wrong tool for this one line.
    """
    out = []
    for arg in command:
        escaped = arg
        for ch in ("\\", '"', "$", "`"):
            escaped = escaped.replace(ch, "\\" + ch)
        out.append(f'"{escaped}"')
    return " ".join(out)


def _write_desktop(path: Path, directory: Path, command: list[str]) -> None:
    """Linux/BSD: a Desktop Entry that opens a terminal for the server log."""
    body = "\n".join(
        [
            "[Desktop Entry]",
            f"# {_BANNER}",
            "Type=Application",
            f"Name={LAUNCHER_NAME}",
            f"Comment={DESCRIPTION}",
            f"Exec={_desktop_quote(command)}",
            f"Path={directory}",
            "Terminal=true",
            "Categories=Graphics;Utility;",
            "",
        ]
    )
    path.write_text(body, encoding="utf-8")
    path.chmod(0o755)


def create_shortcut(directory: str | os.PathLike[str] | None = None) -> Path:
    """Write the launcher for ``directory`` (default: the CWD) and return it.

    Overwrites an existing one — it is a generated file, and the path it pins is
    the thing that goes stale.
    """
    target = Path(directory or Path.cwd()).expanduser().resolve()
    if not target.is_dir():
        raise ShortcutError(f"not a directory: {target}")
    path = launcher_path(target)
    command = gui_command()
    if sys.platform == "win32":
        _write_lnk(path, target, command)
    elif sys.platform == "darwin":
        _write_command(path, target, command)
    else:
        _write_desktop(path, target, command)
    return path


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="anime-tools-shortcut",
        description=(
            "Create a double-clickable launcher for the web GUI in a dataset "
            "folder. The folder it is created in becomes the curation home the "
            "launcher opens, wherever the file itself ends up."
        ),
    )
    p.add_argument(
        "directory",
        nargs="?",
        default=None,
        help="Dataset folder to create it in (default: the current directory)",
    )
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        path = create_shortcut(args.directory)
    except (ShortcutError, OSError) as e:
        print(f"could not create the launcher: {e}", file=sys.stderr)
        return 1
    print(f"launcher: {path}")
    if path.suffix == ".desktop":
        print(
            "  (some file managers ask you to allow launching it the first time)",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
