import { createSignal, type JSX } from "solid-js";

/** The GUI's own chrome, in the four languages the tools are used in.
 *
 * Stage titles, argparse labels and help, and the model catalog's rows are
 * Python-side text and stay as they arrive — re-typing them here is what
 * `frontend/CLAUDE.md` forbids; a caption, a path and a tag are data and are
 * never translated either.
 *
 * `en` is the schema: every other locale is declared `: Dict`, so a missing or
 * misspelled key is a type error rather than a blank label at runtime.
 */
const en = {
  langName: "English",
  common: {
    cancel: "Cancel",
    save: "Save",
    close: "Close",
    browse: "Browse (home-relative)",
    on: "on",
    off: "off",
    running: "running",
    downloading: "downloading",
    installed: "installed",
    missing: "missing",
    present: "present",
    dragToResize: "Drag to resize",
  },
  header: {
    images: (n: number, root: string) => `${n} image${n === 1 ? "" : "s"} in ${root}`,
    noToken: "⚠ no HF token",
    noTokenHint: "The tagger backbone and SAM3 are gated on the Hub — set a token in Settings",
    showSidebar: "Show the dataset sidebar",
  },
  menu: {
    open: "Settings and status",
    settings: "⚙ Settings…",
    advanced: "Advanced",
    models: "Models & weights",
    hfToken: "HF token",
    notSet: "⚠ not set",
    showHelp: "Show explanations",
    language: "Language",
  },
  help: {
    hide: "Hide the description",
    show: "Show the description",
    showWarn: "Show the description (this stage has a warning)",
  },
  tree: {
    modeTree: "tree",
    modeTreeHint: "The folders the dataset is stored in",
    modeGroups: "groups",
    modeGroupsHint: "The near-twin components the Groups stage found",
    rescan: "Rescan the dataset",
    collapse: "Collapse the sidebar",
    filter: "filter…",
    scanning: "scanning…",
    reading: "reading…",
    noImages: "No images match.",
    /** {0} is the root, as a <code>. */
    noRoot: "No {0} under the curation home. Point the roots at your dataset in ⚙ Settings.",
    truncated: (shown: number, total: number) =>
      `showing ${shown} of ${total} — narrow it with the filter`,
    more: (n: number) => `+ ${n} more`,
    capMaster: "master — image_dataset, the hand-written caption",
    capDerived: "derived — post_image_dataset/resized, the stage output",
    capVariants: "variants — .variants.txt, generated and read-only",
    onDisk: "on disk",
    capMissing: "missing",
    flagPending: "the last run proposes a change here",
    flagResized: "resized — post_image_dataset/resized has this image",
    flagMask: "has a mask",
    root: "(root)",
    group: (id: number) => `group ${id}`,
    groupHint: (id: number, cos: number | string) =>
      `component ${id} — mean pairwise CLS cosine ${cos}`,
    ungrouped: "ungrouped",
    /** {0} is the manifest path, as a <code>; {1} the Groups stage's button path. */
    noManifest: "No {0} yet — run {1} in the dock, then come back.",
    buildGroups: "Groups › Build groups",
    staleLabel: "older manifest",
    staleHint: "— rebuild it to pick up the current grouping gate.",
    /** {0} is the manifest path, as a <code>. */
    clustersNothing: "{0} clusters nothing in this listing",
    /** {0} is the directory it was built from, as a <code>. */
    builtFrom: " — it was built from {0}",
  },
  item: {
    loading: "loading…",
    pick: "Pick an image on the left.",
    keys: "↑/↓ or j/k walk the images · ⌘/Ctrl+Enter saves a caption",
    views: {
      image: "source",
      resized: "resized",
      mask: "mask",
      overlay: "overlay",
    },
    overlayHint: "the mask at 40% over the image",
    overlayNeeds: "needs an image and a mask",
    notGenerated: "not generated",
    noOverlay: "no overlay for this image",
    /** e.g. "no mask for this image" — {0} is one of `views`. */
    noView: (view: string) => `no ${view} for this image`,
    overlayOver: (base: string) => `at 40% over ${base}`,
    variants: "variants",
    readOnly: "read-only",
    variantsHint:
      "Generated by the correct stage — v0 is the pristine derived caption. Hand edits here are overwritten.",
    noSidecar: "no sidecar",
  },
  caption: {
    master: "master",
    derived: "derived",
    whereMaster: "hand-written; the stages only read it",
    whereDerived: "stage output; overwritten by the next correct/position run",
    new: "new",
    revert: "Revert",
    save: "Save",
    saveHint: "⌘/Ctrl+Enter",
    empty: "no caption file yet — type one and save",
    saved: "saved — follow with the trainer's TE re-encode",
    savedStale: "saved — .variants.txt is now stale; re-run correct + the trainer's TE re-encode",
    dropped: "diff dropped — the form changed since the run; Run again to recompute",
    noCaption: "no caption",
    tags: (n: number) => `${n} tag${n === 1 ? "" : "s"}`,
    clauses: (n: number) => `${n} clause${n === 1 ? "" : "s"}`,
    unsaved: "unsaved preview",
    lookUpHint: "double-click a tag to look it up",
    bag: "bag",
  },
  diff: {
    proposed: "proposed",
    by: (stage: string) => `by ${stage}`,
    lastRun: "the last run",
    notApplied: "not applied yet",
    stale: "stale",
    staleHint: "the caption changed since the run — Apply will skip it",
    reordered: "same tags, reordered — see the text below.",
  },
  tag: {
    what: (tag: string) => `What is "${tag}"?`,
    posts: (n: string) => `${n} posts`,
    close: "Close (Esc)",
    looking: "looking it up…",
    notInstalled:
      "The Danbooru tag KB is not downloaded. It is what caption correction types tags against — and what this panel reads.",
    getIt: "Get it in Settings › Models",
    unknown: "not a Danbooru tag — an Anima quality tag, a position phrase, or a typo.",
    noDescription: "no wiki description for this tag.",
    matchedAs: (name: string) => `matched as “${name}”.`,
  },
  applyDlg: {
    title: "Apply for real?",
    /** {0} the stage title, {1} the scope (a rel, or the pattern). */
    writesTo: "{0} will write to {1}",
    everyImage: "every image {0} names",
    changes: (n: number) => `— ${n} caption${n === 1 ? "" : "s"} change`,
    /** {0} is <code>--apply</code>. */
    noReport:
      "This stage keeps no replayable report — Apply runs it again with {0}, so it writes what this pass computes.",
    /** {0} is the report path, as a <code>. */
    replay:
      "Writing the run's proposals ({0}) — no model loads. A caption edited since that run is skipped, not overwritten.",
    /** {0} the derived root, {1} `missing`, {2} the master root, {3} the TE target, {4} Undo. */
    where:
      "Caption stages write under {0} (autotag {1} creates masters under {2}). Any caption change must be followed by the trainer's TE re-encode ({3}). {4} puts these captions back, from the same report.",
    apply: "Apply",
  },
  picker: {
    title: "Choose a path",
    use: "Use this folder",
  },
  settings: {
    title: "Settings",
    tabs: { general: "General", advanced: "Advanced", models: "Models" },
    home: "Home",
    modelsDir: "Models dir",
    roots: "Dataset roots",
    /** {0} is <code>out</code>. */
    rootsHelp:
      "Relative to the curation home; the trees are joined by the same relative path. The tools only ever write the workspace — {0} is Export's alone.",
    rootHelp: {
      src: "input — source images + hand-written master captions; never written",
      master: "workspace — revised master captions",
      dst: "workspace — resized images + derived captions + .variants.txt",
      masks: "workspace — {stem}_mask.png, mirroring the source subdirs",
      out: "output — where Export publishes; the tree the trainer reads",
    },
    rootMissing: "missing — ",
    stageDefaults: "Stage defaults",
    /** {0} `--device`, {1} `report_root`, {2} `captions/autotag`, {3} `groups/groups.json`. */
    stageDefaultsHelp:
      "Filled into every stage that takes them, so no stage form re-asks. Leave one blank for the CLI's own default. {0} is not here on purpose: each stage auto-detects it. {1} is the one knob with no flag of its own: each stage keeps its own directory under it ({2}, {3}), so moving the root moves them all without ever pointing two stages at one report — and the curated audit apply reads the audit's report back out of it.",
    reportRootHint: "where every stage's report.json lands — blank = beside the dst root",
    /** {0} is `target_res`. */
    preprocessHelp:
      "Runs over the same images the stage does, so a per-image Apply resizes just that image. Already-current images are skipped, so a re-run is near-free. Tiers must match the trainer's {0}.",
    hf: "Hugging Face",
    token: "Token",
    tokenPlaceholder: "hf_… (stored by huggingface_hub, never shown again)",
    tokenHelp:
      "The tagger backbone and SAM3 weights are gated on the Hub — a token with read access is needed on first run.",
    models: "Models",
    modelsHelp:
      "Every stage fetches what it needs on first use — these buttons only move the wait, and any gated-repo refusal, to a moment you picked. A download runs as a job: one at a time, and it reports here, not in the stage bar, so this dialog can stay open over it.",
    downloadAll: (n: number) => `Download all ${n} missing`,
    allInstalled: "Every model is installed",
    download: "Download",
    redownload: "Re-download",
    downloadingRow: "downloading…",
    /** {0} is the "accept the terms" link. */
    gated: "Gated — {0} with the same account as the token above.",
    gatedLink: "accept the terms",
  },
  stage: {
    run: "Run",
    runBatch: "Run batch",
    apply: "Apply",
    undo: "Undo",
    cancel: "Cancel",
    aim: (rel: string) => `just ${rel}`,
    noImage: "select an image in the sidebar first",
    batchHint: "every image the Settings path_pattern names",
    applyHint: "write what the run proposed",
    undoHint: "put back the captions the last Apply wrote",
    missingModels: (n: number) => `↓ ${n} model${n === 1 ? "" : "s"} missing`,
    missingModelsHint: (names: string) =>
      `Not downloaded yet: ${names}. The first Run fetches them itself — this only moves the wait to a moment you pick.`,
    noStages: "No stages.",
    unavailable: (title: string, error: string) => `${title} is unavailable: ${error}`,
    reinstall: "Reinstall:",
  },
  form: {
    options: "options",
    onePerLine: "one per line",
    reset: "reset to defaults",
  },
  runner: {
    noDryPass: "this stage has no dry pass — Run writes",
    runFirst: "Run first — Apply writes what the run proposed",
    formChanged: "the form changed since the run — Run again",
    noChanges: "that run proposed no changes — nothing to write",
    nothingToUndo: "nothing to undo",
    nothingApplied: "nothing applied yet — Undo puts back an Apply",
    following: (id: string) => `running ${id}`,
    exit: (code: number | null) => `exit ${code}`,
    proposals: (n: number) => `${n} proposal${n === 1 ? "" : "s"}`,
    changed: (n: number) => `${n} file(s) changed`,
    undoing: "undoing…",
    undone: (restored: number, removed: number) =>
      `undone: ${restored} restored, ${removed} removed`,
    skipped: (what: string) => `— skipped ${what}`,
    logClosed: "log stream closed",
  },
  downloads: {
    starting: "starting…",
    finished: "download finished",
  },
};

export type Dict = typeof en;

const ko: Dict = {
  langName: "한국어",
  common: {
    cancel: "취소",
    save: "저장",
    close: "닫기",
    browse: "찾아보기 (홈 기준 상대 경로)",
    on: "켜짐",
    off: "꺼짐",
    running: "실행 중",
    downloading: "내려받는 중",
    installed: "설치됨",
    missing: "없음",
    present: "있음",
    dragToResize: "드래그해서 크기 조절",
  },
  header: {
    images: (n, root) => `${root}에 이미지 ${n}장`,
    noToken: "⚠ HF 토큰 없음",
    noTokenHint: "태거 백본과 SAM3는 허브에서 승인이 필요합니다 — 설정에서 토큰을 넣으세요",
    showSidebar: "데이터셋 사이드바 열기",
  },
  menu: {
    open: "설정과 상태",
    settings: "⚙ 설정…",
    advanced: "고급",
    models: "모델과 가중치",
    hfToken: "HF 토큰",
    notSet: "⚠ 미설정",
    showHelp: "설명 보이기",
    language: "언어",
  },
  help: {
    hide: "설명 숨기기",
    show: "설명 보기",
    showWarn: "설명 보기 (이 스테이지에는 경고가 있습니다)",
  },
  tree: {
    modeTree: "폴더",
    modeTreeHint: "데이터셋이 저장된 폴더 구조",
    modeGroups: "그룹",
    modeGroupsHint: "Groups 스테이지가 찾아낸 근접 쌍 묶음",
    rescan: "데이터셋 다시 훑기",
    collapse: "사이드바 접기",
    filter: "필터…",
    scanning: "훑는 중…",
    reading: "읽는 중…",
    noImages: "조건에 맞는 이미지가 없습니다.",
    noRoot: "큐레이션 홈에 {0}이(가) 없습니다. ⚙ 설정에서 루트를 데이터셋으로 지정하세요.",
    truncated: (shown, total) => `${total}개 중 ${shown}개 표시 — 필터로 좁히세요`,
    more: (n) => `+ ${n}개 더`,
    capMaster: "master — image_dataset, 손으로 쓴 캡션",
    capDerived: "derived — post_image_dataset/resized, 스테이지 출력",
    capVariants: "variants — .variants.txt, 자동 생성이라 읽기 전용",
    onDisk: "디스크에 있음",
    capMissing: "없음",
    flagPending: "마지막 실행이 여기를 바꾸자고 제안했습니다",
    flagResized: "resized — post_image_dataset/resized에 이 이미지가 있습니다",
    flagMask: "마스크 있음",
    root: "(최상위)",
    group: (id) => `그룹 ${id}`,
    groupHint: (id, cos) => `묶음 ${id} — 쌍별 CLS 코사인 평균 ${cos}`,
    ungrouped: "묶이지 않음",
    noManifest: "아직 {0}이(가) 없습니다 — 독에서 {1}을(를) 실행한 뒤 다시 오세요.",
    buildGroups: "Groups › Build groups",
    staleLabel: "예전 매니페스트",
    staleHint: "— 지금의 그룹 판정 기준을 반영하려면 다시 만드세요.",
    clustersNothing: "{0}이(가) 이 목록에서는 아무것도 묶지 못합니다",
    builtFrom: " — {0}을(를) 대상으로 만들어졌습니다",
  },
  item: {
    loading: "불러오는 중…",
    pick: "왼쪽에서 이미지를 고르세요.",
    keys: "↑/↓ 또는 j/k로 이미지 이동 · ⌘/Ctrl+Enter로 캡션 저장",
    views: {
      image: "원본",
      resized: "리사이즈",
      mask: "마스크",
      overlay: "겹쳐 보기",
    },
    overlayHint: "이미지 위에 마스크를 40%로 겹칩니다",
    overlayNeeds: "이미지와 마스크가 모두 있어야 합니다",
    notGenerated: "생성되지 않음",
    noOverlay: "이 이미지에는 겹쳐 볼 것이 없습니다",
    noView: (view) => `이 이미지에는 ${view}이(가) 없습니다`,
    overlayOver: (base) => `${base} 위에 40%로`,
    variants: "variants",
    readOnly: "읽기 전용",
    variantsHint:
      "correct 스테이지가 생성합니다 — v0이 손대지 않은 derived 캡션입니다. 여기서 손으로 고친 내용은 덮어써집니다.",
    noSidecar: "사이드카 없음",
  },
  caption: {
    master: "master",
    derived: "derived",
    whereMaster: "손으로 쓴 캡션; 스테이지는 읽기만 합니다",
    whereDerived: "스테이지 출력; 다음 correct/position 실행이 덮어씁니다",
    new: "신규",
    revert: "되돌리기",
    save: "저장",
    saveHint: "⌘/Ctrl+Enter",
    empty: "아직 캡션 파일이 없습니다 — 입력하고 저장하세요",
    saved: "저장됨 — 이어서 트레이너의 TE 재인코딩을 돌리세요",
    savedStale:
      "저장됨 — .variants.txt가 오래되었습니다; correct와 트레이너의 TE 재인코딩을 다시 돌리세요",
    dropped: "차이 표시를 버렸습니다 — 실행 이후 폼이 바뀌었습니다; 다시 Run 하세요",
    noCaption: "캡션 없음",
    tags: (n) => `태그 ${n}개`,
    clauses: (n) => `절 ${n}개`,
    unsaved: "저장하지 않은 미리보기",
    lookUpHint: "태그를 더블클릭하면 뜻을 찾아봅니다",
    bag: "태그 묶음",
  },
  diff: {
    proposed: "제안",
    by: (stage) => `${stage} 실행 결과`,
    lastRun: "마지막 실행",
    notApplied: "아직 적용 안 됨",
    stale: "오래됨",
    staleHint: "실행 이후 캡션이 바뀌었습니다 — Apply가 이 항목을 건너뜁니다",
    reordered: "태그는 같고 순서만 바뀌었습니다 — 아래 본문을 보세요.",
  },
  tag: {
    what: (tag) => `"${tag}"이(가) 무엇인가요?`,
    posts: (n) => `게시물 ${n}개`,
    close: "닫기 (Esc)",
    looking: "찾는 중…",
    notInstalled:
      "Danbooru 태그 KB가 아직 없습니다. 캡션 교정이 태그를 대조하는 기준이자, 이 패널이 읽는 자료입니다.",
    getIt: "설정 › 모델에서 받기",
    unknown: "Danbooru 태그가 아닙니다 — Anima 품질 태그, 위치 구문, 또는 오타입니다.",
    noDescription: "이 태그에는 위키 설명이 없습니다.",
    matchedAs: (name) => `“${name}”(으)로 찾았습니다.`,
  },
  applyDlg: {
    title: "정말 적용할까요?",
    writesTo: "{0}이(가) {1}에 씁니다",
    everyImage: "{0}이(가) 가리키는 모든 이미지",
    changes: (n) => `— 캡션 ${n}개 변경`,
    noReport:
      "이 스테이지는 다시 재생할 리포트를 남기지 않습니다 — Apply가 {0}를 붙여 다시 실행하므로, 이번 실행이 계산한 결과를 씁니다.",
    replay:
      "실행이 남긴 제안({0})을 씁니다 — 모델을 올리지 않습니다. 그 실행 뒤에 손댄 캡션은 덮어쓰지 않고 건너뜁니다.",
    where:
      "캡션 스테이지는 {0} 아래에 씁니다 (autotag {1}만 {2} 아래에 master를 만듭니다). 캡션을 바꿨다면 반드시 트레이너의 TE 재인코딩({3})을 이어서 돌리세요. {4}는 같은 리포트로 이 캡션들을 되돌립니다.",
    apply: "적용",
  },
  picker: {
    title: "경로 고르기",
    use: "이 폴더 사용",
  },
  settings: {
    title: "설정",
    tabs: { general: "일반", advanced: "고급", models: "모델" },
    home: "홈",
    modelsDir: "모델 폴더",
    roots: "데이터셋 루트",
    rootsHelp:
      "큐레이션 홈 기준 경로입니다; 트리들은 같은 상대 경로로 이어집니다. 도구는 워크스페이스에만 씁니다 — {0}은 Export만 건드립니다.",
    rootHelp: {
      src: "입력 — 원본 이미지와 손으로 쓴 master 캡션; 절대 쓰지 않습니다",
      master: "워크스페이스 — 수정한 master 캡션",
      dst: "워크스페이스 — 리사이즈된 이미지, derived 캡션, .variants.txt",
      masks: "워크스페이스 — {stem}_mask.png, 원본 하위 폴더 구조를 그대로 따릅니다",
      out: "출력 — Export가 내보내는 곳; 트레이너가 읽는 트리",
    },
    rootMissing: "없음 — ",
    stageDefaults: "스테이지 기본값",
    stageDefaultsHelp:
      "이 값을 받는 모든 스테이지에 채워지므로 각 폼이 다시 묻지 않습니다. 비워 두면 CLI 자체 기본값을 씁니다. {0}는 일부러 없습니다: 스테이지마다 알아서 잡습니다. {1}는 자기 플래그가 없는 유일한 값입니다: 스테이지마다 그 아래 자기 폴더({2}, {3})를 쓰므로, 루트를 옮기면 전부 함께 옮겨지면서도 두 스테이지가 한 리포트를 가리키는 일이 없습니다 — 큐레이션 감사 적용도 여기서 감사 리포트를 다시 읽습니다.",
    reportRootHint: "각 스테이지의 report.json이 떨어지는 곳 — 비우면 dst 루트 옆",
    preprocessHelp:
      "스테이지가 다루는 바로 그 이미지들에 대해 돌아가므로, 이미지 하나만 Apply하면 그 이미지만 리사이즈됩니다. 이미 최신인 이미지는 건너뛰므로 다시 돌려도 거의 공짜입니다. 단계 값은 트레이너의 {0}와 맞아야 합니다.",
    hf: "Hugging Face",
    token: "토큰",
    tokenPlaceholder: "hf_… (huggingface_hub이 저장하며, 다시 보여주지 않습니다)",
    tokenHelp:
      "태거 백본과 SAM3 가중치는 허브에서 승인이 필요합니다 — 첫 실행에 읽기 권한 토큰이 필요합니다.",
    models: "모델",
    modelsHelp:
      "모든 스테이지는 처음 쓸 때 필요한 것을 스스로 받습니다 — 이 버튼은 그 기다림과 승인 거절을, 당신이 고른 순간으로 옮길 뿐입니다. 내려받기도 작업으로 돌아갑니다: 한 번에 하나씩이고, 스테이지 바가 아니라 여기에 보고하므로 이 창을 열어 둔 채로 둘 수 있습니다.",
    downloadAll: (n) => `없는 모델 ${n}개 모두 받기`,
    allInstalled: "모든 모델이 설치되어 있습니다",
    download: "받기",
    redownload: "다시 받기",
    downloadingRow: "받는 중…",
    gated: "승인 필요 — 위 토큰과 같은 계정으로 {0}.",
    gatedLink: "약관에 동의",
  },
  stage: {
    run: "실행",
    runBatch: "일괄 실행",
    apply: "적용",
    undo: "되돌리기",
    cancel: "중단",
    aim: (rel) => `${rel} 하나만`,
    noImage: "먼저 사이드바에서 이미지를 고르세요",
    batchHint: "설정의 path_pattern이 가리키는 모든 이미지",
    applyHint: "실행이 제안한 내용을 씁니다",
    undoHint: "마지막 적용이 쓴 캡션을 되돌립니다",
    missingModels: (n) => `↓ 모델 ${n}개 없음`,
    missingModelsHint: (names) =>
      `아직 받지 않음: ${names}. 첫 실행이 알아서 받습니다 — 이 버튼은 그 기다림을 당신이 고른 순간으로 옮길 뿐입니다.`,
    noStages: "스테이지가 없습니다.",
    unavailable: (title, error) => `${title}을(를) 쓸 수 없습니다: ${error}`,
    reinstall: "다시 설치:",
  },
  form: {
    options: "옵션",
    onePerLine: "한 줄에 하나씩",
    reset: "기본값으로 되돌리기",
  },
  runner: {
    noDryPass: "이 스테이지에는 예행 단계가 없습니다 — Run이 곧 쓰기입니다",
    runFirst: "먼저 Run 하세요 — Apply는 실행이 제안한 것을 씁니다",
    formChanged: "실행 이후 폼이 바뀌었습니다 — 다시 Run 하세요",
    noChanges: "그 실행은 바꿀 것을 찾지 못했습니다 — 쓸 내용이 없습니다",
    nothingToUndo: "되돌릴 것이 없습니다",
    nothingApplied: "아직 적용한 것이 없습니다 — Undo는 Apply를 되돌립니다",
    following: (id) => `${id} 실행 중`,
    exit: (code) => `종료 코드 ${code}`,
    proposals: (n) => `제안 ${n}개`,
    changed: (n) => `파일 ${n}개 변경`,
    undoing: "되돌리는 중…",
    undone: (restored, removed) => `되돌림: ${restored}개 복원, ${removed}개 삭제`,
    skipped: (what) => `— 건너뜀 ${what}`,
    logClosed: "로그 스트림이 닫혔습니다",
  },
  downloads: {
    starting: "시작하는 중…",
    finished: "내려받기 완료",
  },
};

const ja: Dict = {
  langName: "日本語",
  common: {
    cancel: "キャンセル",
    save: "保存",
    close: "閉じる",
    browse: "参照（ホームからの相対パス）",
    on: "オン",
    off: "オフ",
    running: "実行中",
    downloading: "ダウンロード中",
    installed: "インストール済み",
    missing: "未取得",
    present: "あり",
    dragToResize: "ドラッグでサイズ変更",
  },
  header: {
    images: (n, root) => `${root} に画像 ${n} 枚`,
    noToken: "⚠ HF トークンなし",
    noTokenHint:
      "タガーのバックボーンと SAM3 は Hub で承認が必要です — 設定でトークンを入れてください",
    showSidebar: "データセットのサイドバーを開く",
  },
  menu: {
    open: "設定とステータス",
    settings: "⚙ 設定…",
    advanced: "詳細",
    models: "モデルと重み",
    hfToken: "HF トークン",
    notSet: "⚠ 未設定",
    showHelp: "説明を表示",
    language: "言語",
  },
  help: {
    hide: "説明を隠す",
    show: "説明を表示",
    showWarn: "説明を表示（このステージには警告があります）",
  },
  tree: {
    modeTree: "フォルダ",
    modeTreeHint: "データセットが置かれているフォルダ構成",
    modeGroups: "グループ",
    modeGroupsHint: "Groups ステージが見つけた近似画像のまとまり",
    rescan: "データセットを再スキャン",
    collapse: "サイドバーを畳む",
    filter: "絞り込み…",
    scanning: "スキャン中…",
    reading: "読み込み中…",
    noImages: "一致する画像がありません。",
    noRoot:
      "キュレーションホームに {0} がありません。⚙ 設定でルートをデータセットに向けてください。",
    truncated: (shown, total) => `${total} 件中 ${shown} 件を表示 — 絞り込みで狭めてください`,
    more: (n) => `+ 他 ${n} 件`,
    capMaster: "master — image_dataset、手書きのキャプション",
    capDerived: "derived — post_image_dataset/resized、ステージの出力",
    capVariants: "variants — .variants.txt、自動生成で読み取り専用",
    onDisk: "ディスク上にあり",
    capMissing: "なし",
    flagPending: "直前の実行がここに変更を提案しています",
    flagResized: "resized — post_image_dataset/resized にこの画像があります",
    flagMask: "マスクあり",
    root: "（ルート）",
    group: (id) => `グループ ${id}`,
    groupHint: (id, cos) => `まとまり ${id} — ペアごとの CLS コサイン平均 ${cos}`,
    ungrouped: "未グループ",
    noManifest: "{0} がまだありません — ドックで {1} を実行してから戻ってください。",
    buildGroups: "Groups › Build groups",
    staleLabel: "古いマニフェスト",
    staleHint: "— 今のグループ判定に合わせるには作り直してください。",
    clustersNothing: "{0} はこの一覧では何もまとめていません",
    builtFrom: " — {0} を対象に作られています",
  },
  item: {
    loading: "読み込み中…",
    pick: "左から画像を選んでください。",
    keys: "↑/↓ または j/k で画像を移動 · ⌘/Ctrl+Enter でキャプションを保存",
    views: {
      image: "元画像",
      resized: "リサイズ",
      mask: "マスク",
      overlay: "重ね表示",
    },
    overlayHint: "画像の上にマスクを 40% で重ねます",
    overlayNeeds: "画像とマスクの両方が必要です",
    notGenerated: "未生成",
    noOverlay: "この画像に重ねるものがありません",
    noView: (view) => `この画像には${view}がありません`,
    overlayOver: (base) => `${base} の上に 40% で`,
    variants: "variants",
    readOnly: "読み取り専用",
    variantsHint:
      "correct ステージが生成します — v0 が手を入れていない derived キャプションです。ここでの手編集は上書きされます。",
    noSidecar: "サイドカーなし",
  },
  caption: {
    master: "master",
    derived: "derived",
    whereMaster: "手書き; ステージは読むだけです",
    whereDerived: "ステージの出力; 次の correct/position 実行で上書きされます",
    new: "新規",
    revert: "元に戻す",
    save: "保存",
    saveHint: "⌘/Ctrl+Enter",
    empty: "キャプションファイルがまだありません — 入力して保存してください",
    saved: "保存しました — 続けてトレーナーの TE 再エンコードを実行してください",
    savedStale:
      "保存しました — .variants.txt が古くなりました; correct とトレーナーの TE 再エンコードをやり直してください",
    dropped: "差分を破棄しました — 実行後にフォームが変わりました; もう一度 Run してください",
    noCaption: "キャプションなし",
    tags: (n) => `タグ ${n} 個`,
    clauses: (n) => `節 ${n} 個`,
    unsaved: "未保存のプレビュー",
    lookUpHint: "タグをダブルクリックすると意味を引きます",
    bag: "タグ袋",
  },
  diff: {
    proposed: "提案",
    by: (stage) => `${stage} による`,
    lastRun: "直前の実行",
    notApplied: "未適用",
    stale: "古い",
    staleHint: "実行後にキャプションが変わりました — Apply はこの行を飛ばします",
    reordered: "タグは同じで並びだけが変わりました — 下の本文を見てください。",
  },
  tag: {
    what: (tag) => `"${tag}" とは？`,
    posts: (n) => `投稿 ${n} 件`,
    close: "閉じる (Esc)",
    looking: "調べています…",
    notInstalled:
      "Danbooru タグ KB が未取得です。キャプション補正がタグを照合する基準であり、このパネルが読むデータです。",
    getIt: "設定 › モデル から取得",
    unknown: "Danbooru のタグではありません — Anima の品質タグ、位置句、または誤字です。",
    noDescription: "このタグには wiki の説明がありません。",
    matchedAs: (name) => `「${name}」として一致しました。`,
  },
  applyDlg: {
    title: "本当に適用しますか？",
    writesTo: "{0} が {1} に書き込みます",
    everyImage: "{0} が指すすべての画像",
    changes: (n) => `— キャプション ${n} 件を変更`,
    noReport:
      "このステージは再生できるレポートを残しません — Apply は {0} を付けて実行し直すので、この回が計算した内容を書きます。",
    replay:
      "実行が残した提案（{0}）を書きます — モデルは読み込みません。その実行後に編集されたキャプションは上書きせず飛ばします。",
    where:
      "キャプションのステージは {0} 以下に書きます（autotag {1} だけが {2} 以下に master を作ります）。キャプションを変えたら必ずトレーナーの TE 再エンコード（{3}）を続けてください。{4} は同じレポートからこれらのキャプションを戻します。",
    apply: "適用",
  },
  picker: {
    title: "パスを選ぶ",
    use: "このフォルダを使う",
  },
  settings: {
    title: "設定",
    tabs: { general: "一般", advanced: "詳細", models: "モデル" },
    home: "ホーム",
    modelsDir: "モデルの場所",
    roots: "データセットのルート",
    rootsHelp:
      "キュレーションホームからの相対パスです; 各ツリーは同じ相対パスで対応づきます。ツールが書くのはワークスペースだけで、{0} は Export 専用です。",
    rootHelp: {
      src: "入力 — 元画像と手書きの master キャプション; 書き込みません",
      master: "ワークスペース — 修正した master キャプション",
      dst: "ワークスペース — リサイズ画像、derived キャプション、.variants.txt",
      masks: "ワークスペース — {stem}_mask.png、元のサブフォルダ構成をそのまま反映します",
      out: "出力 — Export の書き出し先; トレーナーが読むツリー",
    },
    rootMissing: "存在しません — ",
    stageDefaults: "ステージの既定値",
    stageDefaultsHelp:
      "これを受け取るすべてのステージに入るので、各フォームが訊き直しません。空にすると CLI 自身の既定値になります。{0} は意図的にここにありません: 各ステージが自動で判定します。{1} は自分のフラグを持たない唯一の値です: 各ステージがその下に自分のフォルダ（{2}、{3}）を持つので、ルートを動かせば全部が一緒に動きつつ、二つのステージが同じレポートを指すことはありません — キュレーション監査の適用もここから監査レポートを読み直します。",
    reportRootHint: "各ステージの report.json が置かれる場所 — 空なら dst ルートの隣",
    preprocessHelp:
      "ステージが扱うのと同じ画像に対して走るので、画像単位の Apply はその画像だけをリサイズします。すでに最新の画像は飛ばすため、再実行はほぼ無料です。段は トレーナーの {0} と一致させてください。",
    hf: "Hugging Face",
    token: "トークン",
    tokenPlaceholder: "hf_…（huggingface_hub が保存し、二度と表示しません）",
    tokenHelp:
      "タガーのバックボーンと SAM3 の重みは Hub で承認制です — 初回実行に読み取り権限のトークンが要ります。",
    models: "モデル",
    modelsHelp:
      "各ステージは初回利用時に必要なものを自分で取得します — このボタンは、その待ち時間と承認制リポジトリの拒否を、あなたが選んだ瞬間に移すだけです。ダウンロードもジョブとして走ります: 一度に一つで、ステージバーではなくここに報告するので、このダイアログを開いたままにできます。",
    downloadAll: (n) => `未取得の ${n} 件をすべてダウンロード`,
    allInstalled: "すべてのモデルが揃っています",
    download: "ダウンロード",
    redownload: "再ダウンロード",
    downloadingRow: "ダウンロード中…",
    gated: "承認制 — 上のトークンと同じアカウントで{0}してください。",
    gatedLink: "利用規約に同意",
  },
  stage: {
    run: "実行",
    runBatch: "一括実行",
    apply: "適用",
    undo: "元に戻す",
    cancel: "中止",
    aim: (rel) => `${rel} だけ`,
    noImage: "先にサイドバーで画像を選んでください",
    batchHint: "設定の path_pattern が指すすべての画像",
    applyHint: "実行が提案した内容を書き込みます",
    undoHint: "直前の適用が書いたキャプションを戻します",
    missingModels: (n) => `↓ モデル ${n} 件が未取得`,
    missingModelsHint: (names) =>
      `未取得: ${names}。最初の Run が自分で取得します — このボタンは待ち時間をあなたが選んだ瞬間に移すだけです。`,
    noStages: "ステージがありません。",
    unavailable: (title, error) => `${title} は使えません: ${error}`,
    reinstall: "再インストール:",
  },
  form: {
    options: "オプション",
    onePerLine: "1 行に 1 つ",
    reset: "既定値に戻す",
  },
  runner: {
    noDryPass: "このステージにドライ実行はありません — Run がそのまま書き込みます",
    runFirst: "まず Run してください — Apply は実行が提案したものを書きます",
    formChanged: "実行後にフォームが変わりました — もう一度 Run してください",
    noChanges: "その実行は変更を提案しませんでした — 書くものがありません",
    nothingToUndo: "戻すものがありません",
    nothingApplied: "まだ何も適用していません — Undo は Apply を戻します",
    following: (id) => `${id} を実行中`,
    exit: (code) => `終了コード ${code}`,
    proposals: (n) => `提案 ${n} 件`,
    changed: (n) => `ファイル ${n} 件を変更`,
    undoing: "戻しています…",
    undone: (restored, removed) => `戻しました: ${restored} 件復元、${removed} 件削除`,
    skipped: (what) => `— 飛ばした ${what}`,
    logClosed: "ログのストリームが閉じました",
  },
  downloads: {
    starting: "開始しています…",
    finished: "ダウンロード完了",
  },
};

const zh: Dict = {
  langName: "中文",
  common: {
    cancel: "取消",
    save: "保存",
    close: "关闭",
    browse: "浏览（相对于主目录）",
    on: "开",
    off: "关",
    running: "运行中",
    downloading: "下载中",
    installed: "已安装",
    missing: "缺失",
    present: "已设置",
    dragToResize: "拖动调整大小",
  },
  header: {
    images: (n, root) => `${root} 中有 ${n} 张图片`,
    noToken: "⚠ 没有 HF 令牌",
    noTokenHint: "打标模型主干和 SAM3 在 Hub 上需要授权 — 请在设置中填入令牌",
    showSidebar: "展开数据集侧栏",
  },
  menu: {
    open: "设置与状态",
    settings: "⚙ 设置…",
    advanced: "高级",
    models: "模型与权重",
    hfToken: "HF 令牌",
    notSet: "⚠ 未设置",
    showHelp: "显示说明",
    language: "语言",
  },
  help: {
    hide: "隐藏说明",
    show: "显示说明",
    showWarn: "显示说明（此阶段有警告）",
  },
  tree: {
    modeTree: "目录",
    modeTreeHint: "数据集所在的目录结构",
    modeGroups: "分组",
    modeGroupsHint: "Groups 阶段找出的近似图片分组",
    rescan: "重新扫描数据集",
    collapse: "收起侧栏",
    filter: "过滤…",
    scanning: "扫描中…",
    reading: "读取中…",
    noImages: "没有匹配的图片。",
    noRoot: "整理主目录下没有 {0}。请在 ⚙ 设置中把根目录指向你的数据集。",
    truncated: (shown, total) => `共 ${total} 张，显示 ${shown} 张 — 用过滤缩小范围`,
    more: (n) => `+ 还有 ${n} 项`,
    capMaster: "master — image_dataset，手写的标注",
    capDerived: "derived — post_image_dataset/resized，阶段输出",
    capVariants: "variants — .variants.txt，自动生成且只读",
    onDisk: "已在磁盘上",
    capMissing: "缺失",
    flagPending: "上一次运行建议在这里做修改",
    flagResized: "resized — post_image_dataset/resized 中有这张图",
    flagMask: "有掩膜",
    root: "（根目录）",
    group: (id) => `分组 ${id}`,
    groupHint: (id, cos) => `分组 ${id} — 两两 CLS 余弦均值 ${cos}`,
    ungrouped: "未分组",
    noManifest: "还没有 {0} — 先在停靠栏运行 {1}，然后回到这里。",
    buildGroups: "Groups › Build groups",
    staleLabel: "较旧的清单",
    staleHint: "— 重新生成以采用当前的分组判定。",
    clustersNothing: "{0} 在这个列表里没有聚出任何分组",
    builtFrom: " — 它是基于 {0} 生成的",
  },
  item: {
    loading: "加载中…",
    pick: "请在左侧选择一张图片。",
    keys: "↑/↓ 或 j/k 切换图片 · ⌘/Ctrl+Enter 保存标注",
    views: {
      image: "原图",
      resized: "缩放图",
      mask: "掩膜",
      overlay: "叠加",
    },
    overlayHint: "把掩膜以 40% 叠在图片上",
    overlayNeeds: "需要同时有图片和掩膜",
    notGenerated: "尚未生成",
    noOverlay: "这张图没有可叠加的内容",
    noView: (view) => `这张图没有${view}`,
    overlayOver: (base) => `以 40% 叠在 ${base} 上`,
    variants: "variants",
    readOnly: "只读",
    variantsHint: "由 correct 阶段生成 — v0 是未改动的 derived 标注。在这里手改会被覆盖。",
    noSidecar: "没有伴随文件",
  },
  caption: {
    master: "master",
    derived: "derived",
    whereMaster: "手写；各阶段只读取它",
    whereDerived: "阶段输出；会被下一次 correct/position 运行覆盖",
    new: "新建",
    revert: "还原",
    save: "保存",
    saveHint: "⌘/Ctrl+Enter",
    empty: "还没有标注文件 — 输入后保存",
    saved: "已保存 — 接着运行训练器的 TE 重新编码",
    savedStale: "已保存 — .variants.txt 已过期；请重新运行 correct 和训练器的 TE 重新编码",
    dropped: "已丢弃差异 — 运行之后表单变了；请重新 Run",
    noCaption: "没有标注",
    tags: (n) => `${n} 个标签`,
    clauses: (n) => `${n} 个从句`,
    unsaved: "未保存的预览",
    lookUpHint: "双击标签可查询词条",
    bag: "标签集合",
  },
  diff: {
    proposed: "建议",
    by: (stage) => `来自 ${stage}`,
    lastRun: "上一次运行",
    notApplied: "尚未应用",
    stale: "已过期",
    staleHint: "运行之后标注变过 — Apply 会跳过这一条",
    reordered: "标签相同，只是顺序变了 — 见下方文本。",
  },
  tag: {
    what: (tag) => `"${tag}" 是什么？`,
    posts: (n) => `${n} 个作品`,
    close: "关闭 (Esc)",
    looking: "查询中…",
    notInstalled: "还没有下载 Danbooru 标签库。标注纠正用它来核对标签，这个面板读的也是它。",
    getIt: "在 设置 › 模型 中获取",
    unknown: "不是 Danbooru 标签 — 可能是 Anima 质量标签、位置短语，或拼写错误。",
    noDescription: "这个标签没有 wiki 说明。",
    matchedAs: (name) => `按“${name}”匹配到。`,
  },
  applyDlg: {
    title: "确定要应用吗？",
    writesTo: "{0} 将写入 {1}",
    everyImage: "{0} 匹配到的每一张图片",
    changes: (n) => `— 改动 ${n} 条标注`,
    noReport:
      "这个阶段不留可重放的报告 — Apply 会带上 {0} 再跑一次，因此写入的是这一次计算出的结果。",
    replay: "写入这次运行给出的建议（{0}）— 不加载模型。运行之后被编辑过的标注会被跳过，不会覆盖。",
    where:
      "标注类阶段写在 {0} 下（只有 autotag {1} 会在 {2} 下创建 master）。任何标注改动之后都必须运行训练器的 TE 重新编码（{3}）。{4} 会用同一份报告把这些标注放回去。",
    apply: "应用",
  },
  picker: {
    title: "选择路径",
    use: "使用此文件夹",
  },
  settings: {
    title: "设置",
    tabs: { general: "常规", advanced: "高级", models: "模型" },
    home: "主目录",
    modelsDir: "模型目录",
    roots: "数据集根目录",
    rootsHelp:
      "相对于整理主目录；各棵树按同一相对路径对应。工具只写工作区 — {0} 只归 Export 使用。",
    rootHelp: {
      src: "输入 — 源图片和手写的 master 标注；从不写入",
      master: "工作区 — 修订过的 master 标注",
      dst: "工作区 — 缩放图、derived 标注和 .variants.txt",
      masks: "工作区 — {stem}_mask.png，与源子目录结构一致",
      out: "输出 — Export 发布的位置；训练器读取的那棵树",
    },
    rootMissing: "不存在 — ",
    stageDefaults: "阶段默认值",
    stageDefaultsHelp:
      "会填进每个需要它们的阶段，因此各阶段表单不再重复询问。留空则使用 CLI 自己的默认值。{0} 特意不在这里：每个阶段会自动判断。{1} 是唯一没有自己命令行标志的一项：每个阶段在它下面各有自己的目录（{2}、{3}），所以移动根目录会一起移动，且不会让两个阶段指向同一份报告 — 整理审核的应用也从这里回读审核报告。",
    reportRootHint: "各阶段 report.json 的落点 — 留空则放在 dst 根目录旁",
    preprocessHelp:
      "它处理的图片和阶段完全相同，因此对单张图片 Apply 只会缩放那一张。已经是最新的图片会跳过，所以重跑几乎不花代价。档位必须与训练器的 {0} 一致。",
    hf: "Hugging Face",
    token: "令牌",
    tokenPlaceholder: "hf_…（由 huggingface_hub 保存，不会再次显示）",
    tokenHelp: "打标模型主干和 SAM3 权重在 Hub 上需要授权 — 首次运行需要一个有读取权限的令牌。",
    models: "模型",
    modelsHelp:
      "每个阶段首次使用时会自行下载所需内容 — 这些按钮只是把等待，以及授权仓库可能的拒绝，挪到你挑好的时刻。下载也是一个任务：一次一个，并且报告在这里而不是阶段栏，所以这个对话框可以一直开着。",
    downloadAll: (n) => `下载全部 ${n} 个缺失模型`,
    allInstalled: "所有模型都已安装",
    download: "下载",
    redownload: "重新下载",
    downloadingRow: "下载中…",
    gated: "需要授权 — 请用与上面令牌相同的账号{0}。",
    gatedLink: "接受条款",
  },
  stage: {
    run: "运行",
    runBatch: "批量运行",
    apply: "应用",
    undo: "撤销",
    cancel: "中止",
    aim: (rel) => `仅 ${rel}`,
    noImage: "请先在侧栏选择一张图片",
    batchHint: "设置里 path_pattern 匹配到的每一张图片",
    applyHint: "写入这次运行给出的建议",
    undoHint: "把上一次应用写下的标注放回去",
    missingModels: (n) => `↓ 缺 ${n} 个模型`,
    missingModelsHint: (names) =>
      `尚未下载：${names}。第一次 Run 会自行获取 — 这个按钮只是把等待挪到你挑好的时刻。`,
    noStages: "没有阶段。",
    unavailable: (title, error) => `${title} 不可用：${error}`,
    reinstall: "重新安装：",
  },
  form: {
    options: "选项",
    onePerLine: "每行一个",
    reset: "恢复默认值",
  },
  runner: {
    noDryPass: "这个阶段没有试运行 — Run 就是写入",
    runFirst: "请先 Run — Apply 写入的是运行给出的建议",
    formChanged: "运行之后表单变了 — 请重新 Run",
    noChanges: "那次运行没有提出改动 — 没有可写的内容",
    nothingToUndo: "没有可撤销的内容",
    nothingApplied: "还没有应用过 — Undo 撤销的是一次 Apply",
    following: (id) => `正在运行 ${id}`,
    exit: (code) => `退出码 ${code}`,
    proposals: (n) => `${n} 条建议`,
    changed: (n) => `${n} 个文件已变更`,
    undoing: "撤销中…",
    undone: (restored, removed) => `已撤销：恢复 ${restored} 项，删除 ${removed} 项`,
    skipped: (what) => `— 跳过 ${what}`,
    logClosed: "日志流已关闭",
  },
  downloads: {
    starting: "开始中…",
    finished: "下载完成",
  },
};

const DICTS = { en, ko, ja, zh };
export type Locale = keyof typeof DICTS;
/** The picker's order, and the only place a locale id is spelled. */
export const LOCALES = Object.keys(DICTS) as Locale[];
export const localeName = (l: Locale) => DICTS[l].langName;

const KEY = "lang";
const isLocale = (v: string | null): v is Locale => !!v && v in DICTS;

/** A saved choice wins; otherwise the browser's list is walked, so a
    `ko-KR`/`zh-Hans-CN` visitor lands on their own language and everyone else
    on English. */
function initial(): Locale {
  const saved = localStorage.getItem(KEY);
  if (isLocale(saved)) return saved;
  for (const tag of navigator.languages ?? [navigator.language]) {
    const base = tag.toLowerCase().split("-")[0];
    if (base === "zh") return "zh";
    if (isLocale(base)) return base;
  }
  return "en";
}

const [locale, setLocaleSignal] = createSignal<Locale>(initial());
export { locale };

/** Switch language. Written straight to `localStorage` rather than through a
    `createEffect`, because this signal lives at module scope: an effect out
    here would never be owned by a root, and there is only ever one writer. */
export function setLocale(l: Locale) {
  localStorage.setItem(KEY, l);
  document.documentElement.lang = l;
  setLocaleSignal(l);
}
document.documentElement.lang = locale();

/** The strings, in the current language. Reading it inside JSX is what makes a
    language switch re-render the app — every call site is `t().…`. */
export const t = (): Dict => DICTS[locale()];

/** Render a message that has markup in the middle of it.
 *
 * Translations stay plain strings with `{0}`/`{1}` slots — a translator never
 * sees a tag — and the component says what each slot is: a `<code>`, a link, a
 * `<b>`. The alternative was splitting every such sentence into head/tail
 * fragments, which is where word order goes to die in exactly the four
 * languages this file has.
 */
export function slots(text: string, render: (i: number) => JSX.Element): JSX.Element {
  const out: JSX.Element[] = [];
  const re = /\{(\d+)\}/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    if (m.index > last) out.push(text.slice(last, m.index));
    out.push(render(Number(m[1])));
    last = m.index + m[0].length;
  }
  if (last < text.length) out.push(text.slice(last));
  return out;
}
