/** The GUI's own chrome in English, and the schema every other locale is
 * checked against.
 *
 * Stage titles, argparse labels and help, and the model catalog's rows are
 * Python-side text and stay as they arrive — re-typing them here is what
 * `frontend/CLAUDE.md` forbids; a caption, a path and a tag are data and are
 * never translated either.
 *
 * `en` is the schema: every other locale is declared `: Dict` (see `ko.ts`,
 * `ja.ts`, `zh.ts`), so a missing or misspelled key is a type error rather than
 * a blank label at runtime.
 */
const en = {
  langName: "English",
  common: {
    cancel: "Cancel",
    save: "Save",
    close: "Close",
    browse: "Browse (home-relative)",
    on: "on",
    off: "off",
    running: "running",
    downloading: "downloading",
    installed: "installed",
    missing: "missing",
    present: "present",
    dragToResize: "Drag to resize",
  },
  header: {
    images: (n: number, root: string) => `${n} image${n === 1 ? "" : "s"} in ${root}`,
    noToken: "⚠ no HF token",
    noTokenHint: "The tagger backbone and SAM3 are gated on the Hub — set a token in Settings",
    showSidebar: "Show the dataset sidebar",
  },
  menu: {
    open: "Settings and status",
    settings: "⚙ Settings…",
    advanced: "Advanced",
    models: "Models & weights",
    hfToken: "HF token",
    notSet: "⚠ not set",
    showHelp: "Show explanations",
    language: "Language",
  },
  help: {
    hide: "Hide the description",
    show: "Show the description",
    showWarn: "Show the description (this stage has a warning)",
  },
  tree: {
    modeTree: "tree",
    modeTreeHint: "The folders the dataset is stored in",
    modeGroups: "groups",
    modeGroupsHint: "The near-twin components the Groups stage found",
    rescan: "Rescan the dataset",
    collapse: "Collapse the sidebar",
    filter: "filter…",
    scanning: "scanning…",
    reading: "reading…",
    noImages: "No images match.",
    /** {0} is the root, as a <code>. */
    noRoot: "No {0} under the curation home. Point the roots at your dataset in ⚙ Settings.",
    truncated: (shown: number, total: number) =>
      `showing ${shown} of ${total} — narrow it with the filter`,
    more: (n: number) => `+ ${n} more`,
    capMaster: "master — image_dataset, the hand-written caption",
    capHistory: "history — .history.txt, what the revised caption used to say",
    capRevised: "revised — workspace/resized, the stage output",
    capVariants: "variants — .variants.txt, generated and read-only",
    onDisk: "on disk",
    capMissing: "missing",
    flagPending: "the last run changed this image",
    flagResized: "resized — workspace/resized has this image",
    flagMask: "has a mask",
    root: "(root)",
    group: (id: number) => `group ${id}`,
    groupHint: (id: number, cos: number | string) =>
      `component ${id} — mean pairwise CLS cosine ${cos}`,
    ungrouped: "ungrouped",
    /** {0} is the manifest path, as a <code>; {1} the Groups stage's button path. */
    noManifest: "No {0} yet — run {1} in the dock, then come back.",
    buildGroups: "Groups › Build groups",
    staleLabel: "older manifest",
    staleHint: "— rebuild it to pick up the current grouping gate.",
    /** {0} is the manifest path, as a <code>. */
    clustersNothing: "{0} clusters nothing in this listing",
    /** {0} is the directory it was built from, as a <code>. */
    builtFrom: " — it was built from {0}",
  },
  item: {
    loading: "loading…",
    pick: "Pick an image on the left.",
    keys: "↑/↓ or j/k walk the images · ⌘/Ctrl+Enter saves a caption",
    views: {
      image: "source",
      mask: "mask",
      overlay: "overlay",
    },
    overlayHint: "the mask at 40% over the image",
    overlayNeeds: "needs an image and a mask",
    notGenerated: "not generated",
    noOverlay: "no overlay for this image",
    /** e.g. "no mask for this image" — {0} is one of `views`. */
    noView: (view: string) => `no ${view} for this image`,
    readOnly: "read-only",
    /** {0} is the floor, e.g. "0.50 MP". Shown on the pixel-count chip. */
    aboveFloor: (floor: string) => `above the ${floor} resize floor`,
    /** {0} is the floor. Why a stage over this image does nothing at all. */
    belowFloor: (floor: string) =>
      `below the ${floor} resize floor — this image is never resized, so the stages, which walk workspace/resized, see nothing for it. Lower it in ⚙ Settings › Preprocess.`,
    zoomHint: "⌘/Ctrl+scroll magnifies · drag to pan · double-click fits again",
  },
  ocr: {
    title: "text in the image",
    /** {0} is how many lines were recognized. */
    count: (n: number) => `${n} line${n === 1 ? "" : "s"}`,
    readOnly: "generated by the OCR stage",
    scoreHint:
      "the recognizer's mean per-character confidence; vertical Japanese is read sideways and scores low",
    boxHint: "top-left corner in the image, in pixels",
  },
  caption: {
    master: "master",
    history: "history",
    revised: "revised",
    variants: "variants",
    /* One line per ladder rung, looked up as `where_<rung>`: what this version
     *is*, which is the question a badge cannot answer by itself. */
    where_master: "hand-written; the stages only read it",
    where_history: "what this caption used to say, before the run that replaced it",
    where_revised: "stage output; the next run rewrites it and keeps this text as a version",
    where_variants:
      "generated — v0 is the pristine revised caption; a hand edit here is overwritten",
    diffHere: "the last run rewrote this version",
    /** {0} is the version the run wrote, e.g. "revised". */
    diffElsewhere: (kind: string) => `the last run rewrote ${kind} — open it`,
    new: "new",
    revert: "Revert",
    save: "Save",
    saveHint: "⌘/Ctrl+Enter",
    empty: "no caption file yet — type one and save",
    saved: "saved — the previous text is a version above; follow with the trainer's TE re-encode",
    savedStale: "saved — .variants.txt is now stale; re-run correct + the trainer's TE re-encode",
    noCaption: "no caption",
    tags: (n: number) => `${n} tag${n === 1 ? "" : "s"}`,
    clauses: (n: number) => `${n} clause${n === 1 ? "" : "s"}`,
    unsaved: "unsaved preview",
    lookUpHint: "double-click a tag to look it up",
    bag: "bag",
  },
  diff: {
    written: "written",
    by: (stage: string) => `by ${stage}`,
    lastRun: "the last run",
    onDisk: "on disk",
    stale: "superseded",
    staleHint: "the caption changed after this run — what it says now is in the editor above",
    reordered: "same tags, reordered — see the text below.",
  },
  tag: {
    what: (tag: string) => `What is "${tag}"?`,
    posts: (n: string) => `${n} posts`,
    close: "Close (Esc)",
    looking: "looking it up…",
    notInstalled:
      "The Danbooru tag KB is not downloaded. It is what caption correction types tags against — and what this panel reads.",
    getIt: "Get it in Settings › Models",
    unknown: "not a Danbooru tag — an Anima quality tag, a position phrase, or a typo.",
    noDescription: "no wiki description for this tag.",
    matchedAs: (name: string) => `matched as “${name}”.`,
  },
  picker: {
    title: "Choose a path",
    use: "Use this folder",
  },
  settings: {
    /** One per dialog: the three are separate windows, not tabs of one. */
    paneTitle: {
      general: "Settings",
      advanced: "Advanced settings",
      models: "Models & weights",
    },
    home: "Home",
    modelsDir: "Models dir",
    roots: "Dataset roots",
    /** {0} is <code>out</code>. */
    rootsHelp:
      "Relative to the curation home; the trees are joined by the same relative path. The tools only ever write the workspace — {0} is Export's alone.",
    rootHelp: {
      src: "input — source images + hand-written master captions; never written",
      master: "workspace — revised master captions",
      dst: "workspace — resized images + revised captions + their versions + .variants.txt",
      masks: "workspace — {stem}_mask.png, mirroring the source subdirs",
      out: "output — where Export publishes; the tree the trainer reads",
    },
    rootMissing: "missing — ",
    stageDefaults: "Stage defaults",
    /** {0} `--device`, {1} `report_root`, {2} `captions/autotag`, {3} `groups/groups.json`. */
    stageDefaultsHelp:
      "Filled into every stage that takes them, so no stage form re-asks. Leave one blank for the CLI's own default. {0} is not here on purpose: each stage auto-detects it. {1} is the one knob with no flag of its own: each stage keeps its own directory under it ({2}, {3}), so moving the root moves them all without ever pointing two stages at one report — and the curated audit apply reads the audit's report back out of it.",
    reportRootHint: "where every stage's report.json lands — blank = beside the dst root",
    maskRootHint:
      "where each generator's own mask tree lands — blank = beside the masks root the merge fills",
    /** {0} is `target_res`. */
    preprocessHelp:
      "Runs over the same images the stage does, so a per-image Apply resizes just that image. Already-current images are skipped, so a re-run is near-free. Tiers must match the trainer's {0}.",
    hf: "Hugging Face",
    token: "Token",
    tokenPlaceholder: "hf_… (stored by huggingface_hub, never shown again)",
    tokenHelp:
      "The tagger backbone and SAM3 weights are gated on the Hub — a token with read access is needed on first run.",
    models: "Models",
    modelsHelp:
      "Every stage fetches what it needs on first use — these buttons only move the wait, and any gated-repo refusal, to a moment you picked. A download runs as a job: one at a time, and it reports here, not in the stage bar, so this dialog can stay open over it.",
    downloadAll: (n: number) => `Download all ${n} missing`,
    allInstalled: "Every model is installed",
    download: "Download",
    redownload: "Re-download",
    downloadingRow: "downloading…",
    /** {0} is the "accept the terms" link. */
    gated: "Gated — {0} with the same account as the token above.",
    gatedLink: "accept the terms",
  },
  stage: {
    run: "Run",
    runBatch: "Run batch",
    undo: "Undo",
    cancel: "Cancel",
    aim: (rel: string) => `just ${rel}`,
    noImage: "select an image in the sidebar first",
    batchHint: "every image the Settings path_pattern names",
    undoHint: "put back the captions the last run wrote",
    missingModels: (n: number) => `↓ ${n} model${n === 1 ? "" : "s"} missing`,
    missingModelsHint: (names: string) =>
      `Not downloaded yet: ${names}. The first Run fetches them itself — this only moves the wait to a moment you pick.`,
    noStages: "No stages.",
    unavailable: (title: string, error: string) => `${title} is unavailable: ${error}`,
    reinstall: "Reinstall:",
  },
  form: {
    options: "options",
    onePerLine: "one per line",
    reset: "reset to defaults",
    advanced: (n: number) => `▸ advanced (${n})`,
    advancedHide: "▾ advanced",
    advancedHint: "The knobs a run rarely changes its mind about",
    advancedDirty: (n: number) => `${n} hidden field${n === 1 ? " is" : "s are"} off its default`,
  },
  runner: {
    nothingToUndo: "nothing to undo",
    nothingApplied: "nothing run yet — Undo puts back what a run wrote",
    following: (id: string) => `running ${id}`,
    exit: (code: number | null) => `exit ${code}`,
    changed: (n: number) => `${n} file(s) changed`,
    undoing: "undoing…",
    undone: (restored: number, removed: number) =>
      `undone: ${restored} restored, ${removed} removed`,
    skipped: (what: string) => `— skipped ${what}`,
    logClosed: "log stream closed",
  },
  downloads: {
    starting: "starting…",
    finished: "download finished",
  },
};

export default en;
export type Dict = typeof en;
