/** The GUI's own chrome in English, and the schema every other locale is
 * checked against.
 *
 * Stage titles, argparse labels and help, and the model catalog's rows are
 * Python-side text and stay as they arrive — re-typing them here is what
 * `frontend/CLAUDE.md` forbids; a caption, a path and a tag are data and are
 * never translated either.
 *
 * `en` is the schema: every other locale is declared `: Dict` (see `ko.ts`,
 * `ja.ts`, `zh.ts`), so a missing or misspelled key is a type error rather than
 * a blank label at runtime.
 */
const en = {
  langName: "English",
  common: {
    cancel: "Cancel",
    save: "Save",
    close: "Close",
    browse: "Browse (home-relative)",
    on: "on",
    off: "off",
    running: "running",
    downloading: "downloading",
    installed: "installed",
    missing: "missing",
    present: "present",
    dragToResize: "Drag to resize",
  },
  header: {
    images: (n: number, root: string) => `${n} image${n === 1 ? "" : "s"} in ${root}`,
    noToken: "⚠ no HF token",
    noTokenHint: "The tagger backbone and SAM3 are gated on the Hub — set a token in Settings",
    showSidebar: "Show the dataset sidebar",
  },
  menu: {
    open: "Settings and status",
    settings: "⚙ Settings…",
    advanced: "Advanced",
    models: "Models & weights",
    hfToken: "HF token",
    notSet: "⚠ not set",
    showHelp: "Show explanations",
    language: "Language",
  },
  help: {
    hide: "Hide the description",
    show: "Show the description",
    showWarn: "Show the description (this stage has a warning)",
  },
  tree: {
    modeTree: "tree",
    modeTreeHint: "The folders the dataset is stored in",
    modeGroups: "groups",
    modeGroupsHint: "The near-twin components the Groups stage found",
    rescan: "Rescan the dataset",
    collapse: "Collapse the sidebar",
    filter: "filter…",
    scanning: "scanning…",
    reading: "reading…",
    noImages: "No images match.",
    /** {0} is the root, as a <code>. */
    noRoot: "No {0} under the curation home. Point the roots at your dataset in ⚙ Settings.",
    truncated: (shown: number, total: number) =>
      `showing ${shown} of ${total} — narrow it with the filter`,
    more: (n: number) => `+ ${n} more`,
    capMaster: "master — image_dataset, the hand-written caption",
    capDerived: "derived — post_image_dataset/resized, the stage output",
    capVariants: "variants — .variants.txt, generated and read-only",
    onDisk: "on disk",
    capMissing: "missing",
    flagPending: "the last run proposes a change here",
    flagResized: "resized — post_image_dataset/resized has this image",
    flagMask: "has a mask",
    root: "(root)",
    group: (id: number) => `group ${id}`,
    groupHint: (id: number, cos: number | string) =>
      `component ${id} — mean pairwise CLS cosine ${cos}`,
    ungrouped: "ungrouped",
    /** {0} is the manifest path, as a <code>; {1} the Groups stage's button path. */
    noManifest: "No {0} yet — run {1} in the dock, then come back.",
    buildGroups: "Groups › Build groups",
    staleLabel: "older manifest",
    staleHint: "— rebuild it to pick up the current grouping gate.",
    /** {0} is the manifest path, as a <code>. */
    clustersNothing: "{0} clusters nothing in this listing",
    /** {0} is the directory it was built from, as a <code>. */
    builtFrom: " — it was built from {0}",
  },
  item: {
    loading: "loading…",
    pick: "Pick an image on the left.",
    keys: "↑/↓ or j/k walk the images · ⌘/Ctrl+Enter saves a caption",
    views: {
      image: "source",
      mask: "mask",
      overlay: "overlay",
    },
    overlayHint: "the mask at 40% over the image",
    overlayNeeds: "needs an image and a mask",
    notGenerated: "not generated",
    noOverlay: "no overlay for this image",
    /** e.g. "no mask for this image" — {0} is one of `views`. */
    noView: (view: string) => `no ${view} for this image`,
    variants: "variants",
    readOnly: "read-only",
    variantsHint:
      "Generated by the correct stage — v0 is the pristine derived caption. Hand edits here are overwritten.",
    noSidecar: "no sidecar",
    zoomHint: "⌘/Ctrl+scroll magnifies · drag to pan · double-click fits again",
  },
  caption: {
    master: "master",
    derived: "derived",
    whereMaster: "hand-written; the stages only read it",
    whereDerived: "stage output; overwritten by the next correct/position run",
    new: "new",
    revert: "Revert",
    save: "Save",
    saveHint: "⌘/Ctrl+Enter",
    empty: "no caption file yet — type one and save",
    saved: "saved — follow with the trainer's TE re-encode",
    savedStale: "saved — .variants.txt is now stale; re-run correct + the trainer's TE re-encode",
    dropped: "diff dropped — the form changed since the run; Run again to recompute",
    noCaption: "no caption",
    tags: (n: number) => `${n} tag${n === 1 ? "" : "s"}`,
    clauses: (n: number) => `${n} clause${n === 1 ? "" : "s"}`,
    unsaved: "unsaved preview",
    lookUpHint: "double-click a tag to look it up",
    bag: "bag",
  },
  diff: {
    proposed: "proposed",
    by: (stage: string) => `by ${stage}`,
    lastRun: "the last run",
    notApplied: "not applied yet",
    stale: "stale",
    staleHint: "the caption changed since the run — Apply will skip it",
    reordered: "same tags, reordered — see the text below.",
  },
  tag: {
    what: (tag: string) => `What is "${tag}"?`,
    posts: (n: string) => `${n} posts`,
    close: "Close (Esc)",
    looking: "looking it up…",
    notInstalled:
      "The Danbooru tag KB is not downloaded. It is what caption correction types tags against — and what this panel reads.",
    getIt: "Get it in Settings › Models",
    unknown: "not a Danbooru tag — an Anima quality tag, a position phrase, or a typo.",
    noDescription: "no wiki description for this tag.",
    matchedAs: (name: string) => `matched as “${name}”.`,
  },
  applyDlg: {
    title: "Apply for real?",
    /** {0} the stage title, {1} the scope (a rel, or the pattern). */
    writesTo: "{0} will write to {1}",
    everyImage: "every image {0} names",
    changes: (n: number) => `— ${n} caption${n === 1 ? "" : "s"} change`,
    /** {0} is <code>--apply</code>. */
    noReport:
      "This stage keeps no replayable report — Apply runs it again with {0}, so it writes what this pass computes.",
    /** {0} is the report path, as a <code>. */
    replay:
      "Writing the run's proposals ({0}) — no model loads. A caption edited since that run is skipped, not overwritten.",
    /** {0} the derived root, {1} `missing`, {2} the master root, {3} the TE target, {4} Undo. */
    where:
      "Caption stages write under {0} (autotag {1} creates masters under {2}). Any caption change must be followed by the trainer's TE re-encode ({3}). {4} puts these captions back, from the same report.",
    apply: "Apply",
  },
  picker: {
    title: "Choose a path",
    use: "Use this folder",
  },
  settings: {
    title: "Settings",
    tabs: { general: "General", advanced: "Advanced", models: "Models" },
    home: "Home",
    modelsDir: "Models dir",
    roots: "Dataset roots",
    /** {0} is <code>out</code>. */
    rootsHelp:
      "Relative to the curation home; the trees are joined by the same relative path. The tools only ever write the workspace — {0} is Export's alone.",
    rootHelp: {
      src: "input — source images + hand-written master captions; never written",
      master: "workspace — revised master captions",
      dst: "workspace — resized images + derived captions + .variants.txt",
      masks: "workspace — {stem}_mask.png, mirroring the source subdirs",
      out: "output — where Export publishes; the tree the trainer reads",
    },
    rootMissing: "missing — ",
    stageDefaults: "Stage defaults",
    /** {0} `--device`, {1} `report_root`, {2} `captions/autotag`, {3} `groups/groups.json`. */
    stageDefaultsHelp:
      "Filled into every stage that takes them, so no stage form re-asks. Leave one blank for the CLI's own default. {0} is not here on purpose: each stage auto-detects it. {1} is the one knob with no flag of its own: each stage keeps its own directory under it ({2}, {3}), so moving the root moves them all without ever pointing two stages at one report — and the curated audit apply reads the audit's report back out of it.",
    reportRootHint: "where every stage's report.json lands — blank = beside the dst root",
    /** {0} is `target_res`. */
    preprocessHelp:
      "Runs over the same images the stage does, so a per-image Apply resizes just that image. Already-current images are skipped, so a re-run is near-free. Tiers must match the trainer's {0}.",
    hf: "Hugging Face",
    token: "Token",
    tokenPlaceholder: "hf_… (stored by huggingface_hub, never shown again)",
    tokenHelp:
      "The tagger backbone and SAM3 weights are gated on the Hub — a token with read access is needed on first run.",
    models: "Models",
    modelsHelp:
      "Every stage fetches what it needs on first use — these buttons only move the wait, and any gated-repo refusal, to a moment you picked. A download runs as a job: one at a time, and it reports here, not in the stage bar, so this dialog can stay open over it.",
    downloadAll: (n: number) => `Download all ${n} missing`,
    allInstalled: "Every model is installed",
    download: "Download",
    redownload: "Re-download",
    downloadingRow: "downloading…",
    /** {0} is the "accept the terms" link. */
    gated: "Gated — {0} with the same account as the token above.",
    gatedLink: "accept the terms",
  },
  stage: {
    run: "Run",
    runBatch: "Run batch",
    apply: "Apply",
    undo: "Undo",
    cancel: "Cancel",
    aim: (rel: string) => `just ${rel}`,
    noImage: "select an image in the sidebar first",
    batchHint: "every image the Settings path_pattern names",
    applyHint: "write what the run proposed",
    undoHint: "put back the captions the last Apply wrote",
    missingModels: (n: number) => `↓ ${n} model${n === 1 ? "" : "s"} missing`,
    missingModelsHint: (names: string) =>
      `Not downloaded yet: ${names}. The first Run fetches them itself — this only moves the wait to a moment you pick.`,
    noStages: "No stages.",
    unavailable: (title: string, error: string) => `${title} is unavailable: ${error}`,
    reinstall: "Reinstall:",
  },
  form: {
    options: "options",
    onePerLine: "one per line",
    reset: "reset to defaults",
  },
  runner: {
    noDryPass: "this stage has no dry pass — Run writes",
    runFirst: "Run first — Apply writes what the run proposed",
    formChanged: "the form changed since the run — Run again",
    noChanges: "that run proposed no changes — nothing to write",
    nothingToUndo: "nothing to undo",
    nothingApplied: "nothing applied yet — Undo puts back an Apply",
    following: (id: string) => `running ${id}`,
    exit: (code: number | null) => `exit ${code}`,
    proposals: (n: number) => `${n} proposal${n === 1 ? "" : "s"}`,
    changed: (n: number) => `${n} file(s) changed`,
    undoing: "undoing…",
    undone: (restored: number, removed: number) =>
      `undone: ${restored} restored, ${removed} removed`,
    skipped: (what: string) => `— skipped ${what}`,
    logClosed: "log stream closed",
  },
  downloads: {
    starting: "starting…",
    finished: "download finished",
  },
};

export default en;
export type Dict = typeof en;
